M48
; DRILL file {KiCad 9.0.1} date 2025-04-10T12:08:18+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-10T12:08:18+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X128.27Y-85.09
X128.27Y-113.03
X171.45Y-85.09
X171.45Y-113.03
M30
